version: "2"

services:

  sonarqube:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-sonar-pg
    image: kestreltechnology/sq-kt-pg:5.6.0
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    #   - sonarqube_extensions:/opt/sonarqube/extensions/v2
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - db


  db:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-pg
    image: kestreltechnology/pg:5.6.0
    networks:
      - sonarnet
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql/v2
      - postgresql_data:/var/lib/postgresql/v2/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
